### ISSUE TITLE
Couldn't run the demo. Installation requirements failed

### ISSUE THREAD

**Issue by luckychris** [Avaiga/demo-stock-visualization#11]
Hi,

i tried to run this demo, but unfortunately i got this error.

Can you please help me to fix this?
Did i do something wrong?

My machine is a MacBookPro M1. Do you need more informations?

Thanks,
Christoph

Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Building wheels for collected packages: prophet
  Building wheel for prophet (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for prophet (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      /private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.9-universal2-cpython-311/prophet/stan_model
      07:58:31 - cmdstanpy - WARNING - CmdStan installation failed.
      Version 2.26.1 cannot be downloaded. Connection to GitHub failed. Check firewall settings or ensure this version exists.
      CmdStan installation failed.
      Version 2.26.1 cannot be downloaded. Connection to GitHub failed. Check firewall settings or ensure this version exists.
      Compiling cmdstanpy model
      Installing cmdstan to /private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-install-yzy6gj01/prophet_14b54960087f43cdb2f1001fb5add660/build/lib.macosx-10.9-universal2-cpython-311/prophet/stan_model/cmdstan-2.26.1
      CmdStan install directory: /private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-install-yzy6gj01/prophet_14b54960087f43cdb2f1001fb5add660/build/lib.macosx-10.9-universal2-cpython-311/prophet/stan_model
      checking version 2.26.1 availability, retry (1/5)
      checking version 2.26.1 availability, retry (2/5)
      checking version 2.26.1 availability, retry (3/5)
      checking version 2.26.1 availability, retry (4/5)
      checking version 2.26.1 availability, retry (5/5)
      Release 2.26.1 is unavailable from URL https://github.com/stan-dev/cmdstan/releases/download/v2.26.1/cmdstan-2.26.1.tar.gz
      URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 183, in <module>
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/wheel/_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/private/var/folders/ng/2lym57mn3318hnmxs60x4m_40000gn/T/pip-build-env-4wbpjo0k/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 144, in run
        File "<string>", line 131, in build_models
        File "<string>", line 110, in build_cmdstan_model
        File "<string>", line 94, in install_cmdstan_deps
      RuntimeError: CmdStan failed to install in repackaged directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prophet
Failed to build prophet
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (prophet)

**Comment by FlorianJacta** [comment]
Did you create a new environment for your project? It seems like the installation of prophet is not working. Have you installed directly from the requirements.txt?

**Comment by luckychris** [comment]
i have followed the installation.md instructions:

git clone https://github.com/Avaiga/demo-stock-visualization.git
cd demo-stock-visualization
cd src
pip install -r requirements.txt

and that was the result

the error occured when trying to execute pip install... 


tbh i don't know what you mean with "new environment" for your project...

**Comment by FlorianJacta** [comment]
>tbh i don't know what you mean with "new environment" for your project...

It is just a best practice to ensure that there are no conflicts between packages. Here, you have an issue with the *prophet* package, which is a Facebook/Meta package not related to Taipy. It may conflict with packages you have already installed, creating this error.

The goal would be to create a new Python environment to ensure that these conflicts don't appear. There are several ways to do this: conda, pipenv, etc.

For conda after you [install it](https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html), you can create a new environment with:
```
conda create -n new_env python=3.11
conda activate new_env 
pip install -r requirements.txt
```

**Comment by luckychris** [comment]
Thank you for your fast answer. I had to make a "conda init" before activate and restart my terminal (it was written there).
i tried pip install ...afterwards, and got:

![image](https://github.com/user-attachments/assets/222d7bf7-ffee-4e96-ad33-3894d3ff50a7)

**Comment by FlorianJacta** [comment]
So same issue... You can report it to Prophet or find similar issues for your OS/environment. This is not under the Taipy scope unfortunately and it will be hard for me to help
